// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApo1lBt5LLIl3vMCB6JSFvA0w0gVDb5IQ',
    appId: '1:242559262635:web:787c4a504fefca3188bcee',
    messagingSenderId: '242559262635',
    projectId: 'hosna2',
    authDomain: 'hosna2.firebaseapp.com',
    storageBucket: 'hosna2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MtkjxbpLbHJ0LN8c7GhGdPnhzzs_AFQ',
    appId: '1:242559262635:android:f15f54feb25bf71f88bcee',
    messagingSenderId: '242559262635',
    projectId: 'hosna2',
    storageBucket: 'hosna2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiH_1_T1eHISgcPCCQXG3S5OukKaAKc9k',
    appId: '1:242559262635:ios:b4617e3865982df688bcee',
    messagingSenderId: '242559262635',
    projectId: 'hosna2',
    storageBucket: 'hosna2.firebasestorage.app',
    iosBundleId: 'com.waad.hosna',
  );
}
